### ISSUE TITLE
Counter should not have decrement method

### ISSUE THREAD

**Issue by bastiflew** [justeat/JustEat.StatsD#176]
Hello,

a counter should always goes up according to the documentation, there's no decrement.

https://github.com/statsd/statsd/blob/master/docs/metric_types.md#counting

Thanks

**Comment by AnthonySteele** [comment]
I'm sure that I have seen decrements, e.g. https://python-statsd.readthedocs.io/en/latest/statsd.counter.html

It's really an alias for increment by a negative number.

**Comment by bastiflew** [comment]
This is an implementation of the statd specification, but I can't see anywhere that a counter can be decrement: otherwise it's a gauge.

**Comment by AnthonySteele** [comment]
You might be right. "increment" in Statsd is usually used to say that "this thing happened". 
e.g. "a request to this endpoint was handled" "increment by three" means that "this thing happened three times".

`Decrement(3)`, i.e. "increment by -3" means ... what? This thing happened less then zero times? It might not have a meaning at all.

If we find an actual use of it in our code then we should keep it. Otherwise, it can go. 
It's only an extension method.

**Comment by martincostello** [comment]
This doesn't _particularly_ concern me.

Even if we didn't have a decrement method, you'd still be able to do that because the input type is still a signed number, so you could still do this via the increment method anyway.

The integration tests happily work against statsd itself and increment and decrement the counter bucket, so that implies it works, even if it isn't documented. Maybe it's supported as a way to "correct" a mistake in a count before the metric bucket ships somewhere?

_If_ we did want to deprecate this, in the immediate term we'd just add an `[Obsolete]` attribute to the relevant method(s) so that the next release warns consumers and they can move away from it. Then at some future date when there's a genuine need to ship a breaking change as a v5, we could remove it entirely then.

**Comment by martincostello** [comment]
The test that shows that this works is here:

https://github.com/justeat/JustEat.StatsD/blob/40269124d53650ef6d99718d0b06462c95c36dbc/tests/JustEat.StatsD.Tests/IntegrationTests.cs#L40-L95
