### ISSUE TITLE
Provide capability to query health of statsd

### ISSUE THREAD

**Issue by tomkerkhove** [justeat/JustEat.StatsD#246]
Provide capability to query health of statsd server which can be used as a health check to see if the server connection is setup correctly.

**Comment by tomkerkhove** [comment]
Is this something you are planning or provide an alternative approach for?

**Comment by martincostello** [comment]
There's no plan to implement this currently.

While it sounds interesting, I'm not sure if we'd want to start a potentially slippery slope of adding diagnostic/management features into this library.

The only features we provide at the moment are sending metrics to the statsd server.

**Comment by tomkerkhove** [comment]
Thanks for the heads up!

While I fully agree to not go to a management SDK it would be nice to somehow health check the publisher and know it works by integrating it with [.NET Core's health checks](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1) so that we are sure we are up and running.

If the SDK would provide a way to check health I could contribute a health check but there are always boundaries to libraries and respect that!

**Comment by martincostello** [comment]
The publisher is fairly fire-and-forget because it uses UDP, so wouldn't usually throw if the target server isn't there and the metric doesn't actually go anywhere.

Could you resolve `IStatsDPublisher` from DI as part of your health check to validate it? Or are you thinking something more detailed that actually interrogates the server?

There's some (probably hacky) code in our integration tests that queries the server to validate stats are being sent as expected. Maybe you could just lift that and send a stat to a well-known bucket for the server and then read it back?

https://github.com/justeat/JustEat.StatsD/blob/5b78bc6b81808384afe8bad75b941eb78f83ecd5/tests/JustEat.StatsD.Tests/IntegrationTests.cs#L96-L120

**Comment by tomkerkhove** [comment]
I'm injecting it indeed and using that approach but most probably need an approach similar to your tests.

Thanks; I'll work with that!

**Comment by tomkerkhove** [comment]
If I figure it out, are you open for contributions for a new interface?

**Comment by martincostello** [comment]
If it's fairly simple and low maintenance we'd at least consider it, but no promises.

Depending on the solution, we could potentially ship something in an additional package if the only bar was blurring the stats/management boundary.

If it was very very simple though, maybe it could just be a docs thing for the README that people copy-paste, rather than actually shipping the code if it was very trivial.

**Comment by tomkerkhove** [comment]
Makes sense, thanks!
