### ISSUE TITLE
No exception for non-existent host

### ISSUE THREAD

**Issue by PatrikBak** [justeat/JustEat.StatsD#422]
This code

```csharp
var statsDConfig = new StatsDConfiguration
{
    Host = "42.42.42.42",
    OnError = e =>
    {
        Console.WriteLine(e);
        return false;
    }
};
IStatsDPublisher statsDPublisher = new StatsDPublisher(statsDConfig);
while (true)
{
    statsDPublisher.Gauge(new Random().Next(0, 42), "test");
    Thread.Sleep(1000);
}
```

does nothing. What am I doing wrong, please?

net5.0, JustEat.StatsD 4.2.0

**Comment by martincostello** [comment]
I think this is because StatsD uses UDP, the underlying connection to which will behave in this way because transmissions are one-way and never acknowledged.

Essentially, the client app doesn't know the server doesn't exist because it doesn't ever wait for a reply.

**Comment by PatrikBak** [comment]
The same for SocketProtocol = SocketProtocol.IP,

**Comment by martincostello** [comment]
If you're using an IP address (rather than a DNS host), then I believe the same still applies.

Looking at the code, the only difference between the two at the socket level is the `ProtocolType` value passed to the `Socket` constructor:

https://github.com/justeat/JustEat.StatsD/blob/52e16bb8eb772523a7397563f883f15bcd5048f2/src/JustEat.StatsD/SocketFactory.cs#L20-L36

That code path is called here, when creating a new `Socket`:

https://github.com/justeat/JustEat.StatsD/blob/f69602bc3c340e2fe27fe23765810163d4e10a85/src/JustEat.StatsD/ConnectedSocketPool.cs#L30-L43

That's called immediately before using it to send the data:

https://github.com/justeat/JustEat.StatsD/blob/f69602bc3c340e2fe27fe23765810163d4e10a85/src/JustEat.StatsD/SocketTransport.cs#L55-L65

I believe the only place it would throw for an invalid host would be if you gave a DNS host rather than an IP address, in which case the IP lookup would fail here:

https://github.com/justeat/JustEat.StatsD/blob/ec0fd77d847f9b09cfbaaee5d293280c8ec96754/src/JustEat.StatsD/EndpointLookups/DnsLookupIpEndpointSource.cs#L36-L58

If usage of `Socket` isn't throwing an exception in this case, then I think either that's by-design from the protocol within `Socket`, or a bug in `Socket` itself.
